export const backgroundDefaults = {
    scale: 2,
    position: { x: 0, y: -0.6, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    snapToBackground: false,
    snapGridRadius: 1,
    snapGridStep: 0.4,
    snapRayHeight: 200,
    snapMaxDelta: 5,
    snapDebug: false,
    snapMaxY: 2,
    snapPreferHighest: false,
    snapIncludeNames: [],
    snapExcludeNames: [],
};

export const backgroundConfigs = {
    // Example:
    "bus_stop": {
        scale: 2,
        position: { x: 0, y: -1, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        snapToBackground: false,
        snapGridRadius: 0.5,
        snapGridStep: 0.4,
        snapRayHeight: 200,
        snapMaxDelta: 5,
        snapDebug: true,
        snapMaxY: 5,
        snapPreferHighest: false,
        snapIncludeNames: [],
        snapExcludeNames: [],
    },
    "beach": {
        scale: 0.25,
        position: { x: -6, y: -5, z: -15 },
        rotation: { x: 0, y: 10, z: 0 },
        snapToBackground: false,
        snapGridRadius: 0.1,
        snapGridStep: 0.4,
        snapRayHeight: 200,
        snapMaxDelta: 5,
        snapDebug: false,
        snapMaxY: 2,
        snapPreferHighest: false,
        snapIncludeNames: [],
        snapExcludeNames: [],
    },
    "ballpark": {
        scale: 0.03,
        position: { x: 0, y: -0.3, z: -4 },
        rotation: { x: 0, y: -0.5, z: 0 },
        snapToBackground: false,
        snapGridRadius: 0.1,
        snapGridStep: 0.4,
        snapRayHeight: 200,
        snapMaxDelta: 4.8,
        snapDebug: true,
        snapMaxY: 2,
        snapPreferHighest: true,
        snapIncludeNames: ['ground', 'grass'],
        snapExcludeNames: ['shade'],
    }
};
